version: '3'

services:
  gateway:
    build:
      context: nginx
    container_name: gateway
    #entrypoint: dockerize -wait tcp://app:3000 -timeout 50s;
    networks:
      - desafio-node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app  
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    networks:
      - desafio-node-network
    volumes:
      - type: bind
        source: ./node
        target: /usr/src/app
    tty: true   
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-node-network
    ports:
      - "3306"

networks:
  desafio-node-network:
    driver: bridge
  