FROM nginx:1.15.0-alpine

# Removendo as configurações basicas/default do nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/www/html -p && touch /var/www/html/index.php

#COPY html /usr/share/nginx/html

#ENTRYPOINT["/docker-entrypoint.sh"]
#CMD ["nginx", "-g", "daemon off;"]
